# Generated by Django 5.2.4 on 2025-08-03 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('form', 'Form Input'), ('email', 'Send Email'), ('timer', 'Delay Timer'), ('approval', 'Approval Step'), ('condition', 'Conditional Branch'), ('webhook', 'Webhook Call')], max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('file', 'File'), ('number', 'Number'), ('date', 'Date'), ('choice', 'Dropdown')], max_length=50)),
                ('required', models.BooleanField(default=True)),
                ('choices', models.TextField(blank=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.workflowstep')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('done', 'Done'), ('skipped', 'Skipped'), ('error', 'Error')], max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='core.workflowexecution')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workflowstep')),
            ],
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='current_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstepexecution'),
        ),
    ]
