# Generated by Django 5.2.4 on 2025-08-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='choices',
            field=models.TextField(blank=True, help_text='CSV format, e.g., Option1,Option2'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('file', 'File'), ('number', 'Number'), ('password', 'Password'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime'), ('range_date', 'Date Range'), ('range_time', 'Time Range'), ('range_datetime', 'DateTime Range'), ('choice', 'Dropdown'), ('multi_choice', 'Multi-Select'), ('checkbox', 'Checkbox'), ('section_heading', 'Section Heading'), ('html_note', 'HTML Note')], max_length=50),
        ),
    ]
