# Generated by Django 5.2.4 on 2025-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_formfield_choices_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstepexecution',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('running', 'Running'), ('done', 'Done'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
