# Generated by Django 5.2.4 on 2025-08-09 14:32

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('website', '0003_navigationsettings_navigationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('hero', 5), ('hero_slider', 7), ('feature_list', 9), ('richtext', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('image', 2), ('cta_text', 3), ('cta_url', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('image', 2), ('heading', 3), ('subheading', 1), ('cta_text', 3), ('cta_url', 4)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 1), ('icon', 3)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.RichTextBlock', (), {})}),
        ),
        migrations.CreateModel(
            name='UXSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(blank=True, max_length=200)),
                ('show_announcement', models.BooleanField(default=False)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g., X, Facebook, LinkedIn', max_length=20)),
                ('url', models.URLField()),
                ('sort', models.PositiveIntegerField(default=0)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='website.uxsettings')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('external_url', models.URLField(blank=True)),
                ('group', models.CharField(choices=[('about', 'About'), ('resources', 'Resources'), ('legal', 'Legal')], default='about', max_length=20)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='website.uxsettings')),
            ],
            options={
                'ordering': ['group', 'sort', 'id'],
            },
        ),
    ]
