# Generated by Django 5.2.4 on 2025-08-09 15:18

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('website', '0004_alter_homepage_content_uxsettings_sociallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uxsettings',
            name='footer_gap_px',
            field=models.PositiveIntegerField(default=24, help_text='Gap between groups in pixels.'),
        ),
        migrations.AddField(
            model_name='uxsettings',
            name='footer_groups_per_row',
            field=models.PositiveIntegerField(default=3, help_text='How many link groups per row on desktop (e.g., 3).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AddField(
            model_name='uxsettings',
            name='footer_pad_x_px',
            field=models.PositiveIntegerField(default=12, help_text='Horizontal padding (px) inside the footer container.'),
        ),
        migrations.AddField(
            model_name='uxsettings',
            name='footer_pad_y_px',
            field=models.PositiveIntegerField(default=40, help_text='Vertical padding (px) for the main footer section.'),
        ),
        migrations.CreateModel(
            name='FooterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_groups', to='website.uxsettings')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('external_url', models.URLField(blank=True)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='website.footergroup')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
    ]
