# Generated by Django 5.2.4 on 2025-08-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_uxsettings_footer_groups_per_row_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uxsettings',
            name='footer_gap_px',
        ),
        migrations.RemoveField(
            model_name='uxsettings',
            name='footer_groups_per_row',
        ),
        migrations.RemoveField(
            model_name='uxsettings',
            name='footer_pad_x_px',
        ),
        migrations.RemoveField(
            model_name='uxsettings',
            name='footer_pad_y_px',
        ),
    ]
