# Generated by Django 5.2.4 on 2025-08-09 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_uxsettings_footer_gap_px_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footeritem',
            name='group',
        ),
        migrations.RemoveField(
            model_name='footeritem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='settings',
        ),
        migrations.DeleteModel(
            name='FooterGroup',
        ),
        migrations.DeleteModel(
            name='FooterItem',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
