# Generated by Django 5.2.4 on 2025-08-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Portal Access',
                'verbose_name_plural': 'Portal Access',
                'permissions': [('portal_access', 'Can access the unified portal'), ('portal_admin', 'Can administer the portal'), ('appointments_view', 'Can view appointments in portal'), ('leave_submit', 'Can submit leave requests in portal'), ('purchase_submit', 'Can submit purchase requests in portal')],
            },
        ),
    ]
