# Generated by Django 5.2.4 on 2025-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentchild',
            options={'verbose_name': 'Parent–child link', 'verbose_name_plural': 'Parent–child links'},
        ),
        migrations.RemoveField(
            model_name='parentchild',
            name='relation',
        ),
        migrations.AddField(
            model_name='parentchild',
            name='child_relation',
            field=models.CharField(choices=[('child', 'Child'), ('daughter', 'Daughter'), ('son', 'Son'), ('ward', 'Ward'), ('other', 'Other')], default='child', max_length=20),
        ),
        migrations.AddField(
            model_name='parentchild',
            name='guardian_role',
            field=models.CharField(choices=[('guardian', 'Guardian'), ('mother', 'Mother'), ('father', 'Father'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], default='guardian', max_length=20),
        ),
        migrations.AddField(
            model_name='parentchild',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='parentchild',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('child')), _negated=True), name='pc_parent_not_child'),
        ),
    ]
