# Generated by Django 5.2.4 on 2025-08-08 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_parentchild_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_parent',
            new_name='is_guardian',
        ),
        migrations.CreateModel(
            name='GuardianChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_role', models.CharField(choices=[('guardian', 'Guardian'), ('mother', 'Mother'), ('father', 'Father'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], default='guardian', max_length=20)),
                ('child_relation', models.CharField(choices=[('child', 'Child'), ('daughter', 'Daughter'), ('son', 'Son'), ('ward', 'Ward'), ('other', 'Other')], default='child', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian–child link',
                'verbose_name_plural': 'Guardian–child links',
            },
        ),
        migrations.DeleteModel(
            name='ParentChild',
        ),
        migrations.AddConstraint(
            model_name='guardianchild',
            constraint=models.CheckConstraint(condition=models.Q(('guardian', models.F('child')), _negated=True), name='pc_guardian_not_child'),
        ),
        migrations.AlterUniqueTogether(
            name='guardianchild',
            unique_together={('guardian', 'child')},
        ),
    ]
