# Generated by Django 5.2.4 on 2025-08-09 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_is_parent_user_is_guardian_guardianchild_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guardianchild',
            options={'ordering': ['child', '-is_primary', 'guardian_role', 'guardian_id'], 'verbose_name': 'Guardian–child link', 'verbose_name_plural': 'Guardian–child links'},
        ),
        migrations.AddField(
            model_name='guardianchild',
            name='can_pickup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='guardianchild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 9, 11, 34, 43, 339722)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianchild',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardianchild',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardianchild',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardianchild',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='guardianchild',
            index=models.Index(fields=['guardian'], name='accounts_gu_guardia_264e73_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianchild',
            index=models.Index(fields=['child'], name='accounts_gu_child_i_2f6bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianchild',
            index=models.Index(fields=['child', 'is_primary'], name='accounts_gu_child_i_514b93_idx'),
        ),
    ]
