# Generated by Django 5.2.4 on 2025-08-13 08:58

from django.db import migrations

ROLE_GROUPS = [
    "role_student",
    "role_faculty",
    "role_staff",
    "role_parent",
    "role_external",
]


def create_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ROLE_GROUPS:
        Group.objects.get_or_create(name=name)


class Migration(migrations.Migration):
    # 👇 make this depend on your latest migration in 'accounts'
    dependencies = [
        ("accounts", "0005_alter_guardianchild_options_guardianchild_can_pickup_and_more"),
    ]

    operations = [
        migrations.RunPython(create_role_groups, reverse_code=migrations.RunPython.noop),
    ]
