# Generated by Django 5.2.4 on 2025-08-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(choices=[('azure', 'Microsoft Entra ID (Azure AD)'), ('google', 'Google Workspace')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('schedule_kind', models.CharField(choices=[('interval', 'Interval (minutes)'), ('cron', 'Cron expression')], default='interval', max_length=10)),
                ('interval_minutes', models.PositiveIntegerField(default=60)),
                ('cron_expr', models.CharField(blank=True, max_length=100)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('allowed_domains', models.JSONField(blank=True, default=list)),
                ('include_groups', models.BooleanField(default=True)),
                ('include_licenses', models.BooleanField(default=True)),
                ('deprovision_missing', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, max_length=20)),
                ('last_error', models.TextField(blank=True)),
                ('delta_link', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('deactivated_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory_sync.externaldirectory')),
            ],
        ),
    ]
