# Generated by Django 5.2.4 on 2025-08-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externaldirectory',
            options={'verbose_name': 'External directory', 'verbose_name_plural': 'External directories'},
        ),
    ]
