# Generated by Django 5.2.4 on 2025-08-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_sync', '0003_alter_syncjob_options_externaldirectory_only_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldirectory',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list, help_text='Optional allow-list of email domains to keep (e.g., ["school.edu"]). '),
        ),
    ]
