# Generated by Django 5.2.4 on 2025-08-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory_sync', '0004_alter_externaldirectory_allowed_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldirectory',
            name='delta_link',
            field=models.TextField(blank=True, help_text='Microsoft Graph delta cursor. Managed automatically; clearing forces a fresh delta crawl.'),
        ),
    ]
